apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::913524941205:role/eksctl-eks-cluster-nodegroup-Expen-NodeInstanceRole-q4yJ9ZOY8fye
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
  - groups:
    - pod-reader-for-rbac
    userarn: arn:aws:iam::913524941205:user/for-rbac
    username: for-rbac
kind: ConfigMap
metadata:
  creationTimestamp: "2024-10-12T05:29:02Z"
  name: aws-auth
  namespace: kube-system
  uid: 8e2148b6-cf9f-45be-866b-ca38019414e5 # dont change

